# Generated by Django 4.2 on 2023-04-07 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0007_rename_trait_name_trait_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
