# Generated by Django 4.2 on 2023-04-07 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0008_alter_trait_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
